ocr/urls.py
from django.urls import path

from . import views
from django.views.decorators.csrf import csrf_exempt

app_name = 'ocr'
urlpatterns = [
    path('', views.index, name='index'),
    path('upload_image', csrf_exempt(views.upload_image), name='upload_image'),
    path('get_crop_and_ocr', csrf_exempt(views.get_crop_and_ocr), name='get_crop_and_ocr'),
]

web_ocr/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('ocr.urls')),
    path('ocr/', include('ocr.urls')),
    path('admin/', admin.site.urls),
]

ocr/models.py
from django.db import models
from django.utils import timezone
import datetime

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

def was_published_recently(self):
    return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

ocr/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.core.files.storage import FileSystemStorage

from django.conf import settings
import os
import cv2
#from .ocr_image import app
import shutil

def index(request):
    return render(request, 'ocr/detail.html')


def load_image(filename):
    img = cv2.imread(str(os.path.join(settings.BASE_DIR,'images')) + filename)
    img = None
    return img

def delete_image(filename):
    os.remove(str(os.path.join(settings.BASE_DIR,'images')) + filename)

def upload_image(request):
    # question = get_object_or_404(Question, pk=question_id)
    if request.method == 'POST':
        image = request.FILES['myfile']
        fs = FileSystemStorage(location=os.path.join(settings.BASE_DIR,'images'))
        filename = fs.save(image.name, image)
        uploaded_file_url = fs.url(filename)
        img = load_image(uploaded_file_url)
        #model = os.path.join(settings.BASE_DIR, 'model')
        #tessdata_dir_config = r'--tessdata-dir ' + str(model)
        #uuid = app.main(img)
        uuid = None
        delete_image(uploaded_file_url)
        if(uuid is  None):
            uuid = "Please upload image again for OCR"
        return render(request, 'ocr/upload.html', {
            'message': uuid,
        })
#
#
def make_archive(uuid,path):
    shutil.make_archive(uuid, 'zip', path)
    try:
        dest = shutil.move(os.path.join(settings.BASE_DIR,str(uuid)+'.zip'), os.path.join(settings.BASE_DIR,'zips'))
    except(shutil.Error):
        os.remove(str(os.path.join(settings.BASE_DIR,str(uuid)+'.zip')))
        dest = os.path.join(os.path.join(settings.BASE_DIR,'zips'),str(uuid)+'.zip')
    return dest
def get_crop_and_ocr(request):
    if(request.method == 'POST'):
        uuid = request.POST['uuid']
        path = os.path.join(settings.BASE_DIR, 'Outputs'+'/'+uuid)
        try :
            zip_file = make_archive(uuid,path)
            message = "Download file"
            response = HttpResponse(open(zip_file, 'rb'), content_type='application/force-download')
            response['Content-Disposition'] = 'attachment; filename="%s"' % str(uuid)+'.zip'
            return response
        except FileNotFoundError :
            message = "File Not Exist, Please do OCR again"
            return HttpResponse(message)

ocr/templates/ocr/detail.html
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<p>
    Upload Image for OCR
</p>

<form action="{% url 'ocr:upload_image' %}" method="post" enctype="multipart/form-data">
{% csrf_token %}
{#{% for choice in question.choice_set.all %}#}
{#    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">#}
{#    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>#}
{#{% endfor %}#}
 <input type="file" name="myfile">
<input type="submit" value="Upload">
</form>

<p>
    Enter uuid for retrieve cropped image with text.
</p>
<form action="{% url 'ocr:get_crop_and_ocr' %}" method="post" enctype="multipart/form-data">
{% csrf_token %}
    <input type="text" name="uuid">
    <input type="submit" value="Submit">
</form>

ocr/templates/ocr/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="/ocr/{{ question.id }}/">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

ocr/templates/ocr/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'ocr:detail' question.id %}">Vote again?</a>

ocr/templates/ocr/upload.html
{% if message %}<p><strong>{{ message }}</strong></p>{% endif %}